[package]
name = "wd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.19"
log = "0.4.17"
memmap = "0.7.0"
